<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>MathTools.Console</RootNamespace>
    <AssemblyName>MathTools.Console</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Math.Core\Math.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="qpData.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
